### PR TITLE
Dpr2 337 update lib version to include cache

### PR DESCRIPTION
**Pull request by gavriil-g-moj**
Enabling cache for the reporting mi application.

### CODE REVIEW

**Comment by tom-ogle-moj** [comment]
The build is failing with `Could not find uk.gov.justice.service.hmpps:hmpps-digital-prison-reporting-lib:2.0.3`

**Comment by gavriil-g-moj** [comment]
> The build is failing with `Could not find uk.gov.justice.service.hmpps:hmpps-digital-prison-reporting-lib:2.0.3`

Yes, version 2.0.3 of the library was published earlier today but it takes some time to become available.

**Comment by gavriil-g-moj** [comment]
> > The build is failing with `Could not find uk.gov.justice.service.hmpps:hmpps-digital-prison-reporting-lib:2.0.3`
> 
> Yes, version 2.0.3 of the library was published earlier today but it takes some time to become available.

It is fine now.

**Review by tom-ogle-moj — APPROVED** [review]
LGTM

**Pull request merged**
